apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "producer-rss.fullname" . }}
  labels:
    {{- include "producer-rss.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "producer-rss.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        networking.k8s.io/network-policy: producer-rss-allow-fetch-from-internet
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "producer-rss.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "producer-rss.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_RESOLVER_BACKOFF
              value: "{{ .Values.api.resolver.backoff }}"
            - name: API_RESOLVER_URI
              value: "{{ .Values.api.resolver.uri }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
            - name: FEED_TLS_SKIP_VERIFY
              value: "{{ .Values.feed.tls.skipVerify }}"
            - name: FEED_UPDATE_INTERVAL_MIN
              value: "{{ .Values.feed.updateInterval.min }}"
            - name: FEED_UPDATE_INTERVAL_MAX
              value: "{{ .Values.feed.updateInterval.max }}"
            - name: FEED_UPDATE_TIMEOUT
              value: "{{ .Values.feed.updateTimeout }}"
            - name: FEED_USER_AGENT
              value: "{{ .Values.feed.userAgent }}"
            - name: MSG_MD_KEY_FEED_CATEGORIES
              value: "{{ .Values.message.metadata.key.feedCategories }}"
            - name: MSG_MD_KEY_FEED_DESCRIPTION
              value: "{{ .Values.message.metadata.key.feedDescription }}"
            - name: MSG_MD_KEY_FEED_IMAGE_TITLE
              value: "{{ .Values.message.metadata.key.feedImageTitle }}"
            - name: MSG_MD_KEY_FEED_IMAGE_URL
              value: "{{ .Values.message.metadata.key.feedImageUrl }}"
            - name: MSG_MD_KEY_FEED_TITLE
              value: "{{ .Values.message.metadata.key.feedTitle }}"
            - name: MSG_MD_KEY_AUTHOR
              value: "{{ .Values.message.metadata.key.author }}"
            - name: MSG_MD_KEY_CATEGORIES
              value: "{{ .Values.message.metadata.key.categories }}"
            - name: MSG_MD_KEY_GUID
              value: "{{ .Values.message.metadata.key.guid }}"
            - name: MSG_MD_KEY_IMAGE_TITLE
              value: "{{ .Values.message.metadata.key.imageTitle }}"
            - name: MSG_MD_KEY_IMAGE_URL
              value: "{{ .Values.message.metadata.key.imageUrl }}"
            - name: MSG_MD_KEY_LANGUAGE
              value: "{{ .Values.message.metadata.key.language }}"
            - name: MSG_MD_KEY_SUMMARY
              value: "{{ .Values.message.metadata.key.summary }}"
            - name: MSG_MD_KEY_TITLE
              value: "{{ .Values.message.metadata.key.title }}"
            - name: MSG_MD_SPEC_VERSION
              value: "{{ .Values.message.metadata.specVersion }}"
            - name: MSG_CONTENT_TYPE
              value: "{{ .Values.message.content.type }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe: null
          readinessProbe: null
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/feed-urls.txt
              name: {{ .Release.Name }}-feed-urls-config
              subPath: feed-urls.txt
      volumes:
        - name: {{ .Release.Name }}-feed-urls-config
          configMap:
            name: {{ .Release.Name }}-feed-urls-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
