name: Staging

on:
  push:
    branches:
      - "master"

jobs:

  staging:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Staging
        run: make staging
